export const API_URI_AUTH = 'https://unsplash.com/oauth/authorize';
export const REDIRECT_URI = 'https://photo-gallery-liard.vercel.app/'; // https://photo-gallery-liard.vercel.app
export const ACCESS_KEY = 'VZXhuPYL2cX5Xc0K6Km7FYKNlZ5Kgl14Kdi-vT_yeB0';
export const SECRET_KEY = 'IwHM68zkE9Lt4EBOZzd7R8vJ-L5_lVEnJoPIPca03VM';
export const RESPONSE_TYPE = 'code';
export const SCOPE = 'public read_user read_photos write_likes';
export const API_URI_TOKEN = 'https://unsplash.com/oauth/token';
export const GRANT_TYPE = 'authorization_code';
export const API_URI = 'https://api.unsplash.com/';
